INSERT INTO company(name) VALUES("Dell");
INSERT INTO company(name) VALUES("Lenovo");
INSERT INTO company(name) VALUES("Apple");


INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4500 Jean",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4500 Paul",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4500 Pierre",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4500 Luc",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4500 Saturnin",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4500 Jeanne",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4500 Tarzan",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4500 Stephane",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4500 Obi Wan",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4500 Bart",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4500 Homer",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4500 Carter",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4600 Luc",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4600 Loic",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4600 Charles",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision M4600 Michael",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision T3400 Luc",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision T3400 Chuck",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision T3500 Luc",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Precision T3500 Sarah",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Vostro 1710 Sarah",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Vostro 1710 Jacques",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Vostro 1710 Luc",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Vostro 1720 Sally",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("Vostro 1720 Luc",NULL,NULL,1);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("ThinkPad W520 Luc",NULL,NULL,2);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("ThinkPad W520 Clark",NULL,NULL,2);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("ThinkPad W520 Lois",NULL,NULL,2);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("ThinkPad W520 Cheetah",NULL,NULL,2);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("ThinkPad T410 Lisa",NULL,NULL,2);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("ThinkPad T410 Luc",NULL,NULL,2);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("ThinkPad T410 Laura",NULL,NULL,2);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("MacBook Pro 15",NULL,NULL,3);
INSERT INTO computer (name,introduced,discontinued,id_company) VALUES ("MacBook Pro 14",NULL,NULL,3);