CALL addCompany("Dell");
CALL addCompany("Lenovo");
CALL addCompany("Apple");

CALL addComputer("Precision M4500 Jean",NULL,NULL,1);
CALL addComputer("Precision M4500 Paul",NULL,NULL,1);
CALL addComputer("Precision M4500 Pierre",NULL,NULL,1);
CALL addComputer("Precision M4500 Luc",NULL,NULL,1);
CALL addComputer("Precision M4500 Saturnin",NULL,NULL,1);
CALL addComputer("Precision M4500 Jeanne",NULL,NULL,1);
CALL addComputer("Precision M4500 Tarzan",NULL,NULL,1);
CALL addComputer("Precision M4500 Stephane",NULL,NULL,1);
CALL addComputer("Precision M4500 Obi Wan",NULL,NULL,1);
CALL addComputer("Precision M4500 Bart",NULL,NULL,1);
CALL addComputer("Precision M4500 Homer",NULL,NULL,1);
CALL addComputer("Precision M4500 Carter",NULL,NULL,1);
CALL addComputer("Precision M4600 Luc",NULL,NULL,1);
CALL addComputer("Precision T3400 Luc",NULL,NULL,1);
CALL addComputer("Precision T3400 Chuck",NULL,NULL,1);
CALL addComputer("Precision T3500 Luc",NULL,NULL,1);
CALL addComputer("Precision T3500 Sarah",NULL,NULL,1);
CALL addComputer("Vostro 1710 Sarah",NULL,NULL,1);
CALL addComputer("Vostro 1710 Jacques",NULL,NULL,1);
CALL addComputer("Vostro 1710 Luc",NULL,NULL,1);
CALL addComputer("Vostro 1720 Sally",NULL,NULL,1);
CALL addComputer("Vostro 1720 Luc",NULL,NULL,1);
CALL addComputer("ThinkPad W520 Luc",NULL,NULL,2);
CALL addComputer("ThinkPad W520 Clark",NULL,NULL,2);
CALL addComputer("ThinkPad W520 Lois",NULL,NULL,2);
CALL addComputer("ThinkPad W520 Cheetah",NULL,NULL,2);
CALL addComputer("ThinkPad T410 Lisa",NULL,NULL,2);
CALL addComputer("ThinkPad T410 Luc",NULL,NULL,2);